// Run with: unity command eval_file --file Tests/DestinationChecks.cs
void Check(bool ok, string message) { if (!ok) throw new System.Exception(message); }
CardData Card(string name, string type) => new CardData { name = name, type = type, attack = 2, defense = 2 };
var r = new MatchRules();
var vale = Card("Vale", "Land"); var hills = Card("Hills", "Land");
var home = Card("Home", "PC"); home.region = "Vale"; home.objectTypes.Add(ObjectTypeEnum.Weapon);
var market = Card("Market", "PC"); market.region = "Vale"; market.objectTypes.Add(ObjectTypeEnum.Ring); market.objectTypes.Add(ObjectTypeEnum.Remedy);
var far = Card("Far Hold", "PC"); far.region = "Hills";
r.Players[0].Settlements.AddRange(new[] { home, market, far });
var hero = Card("Hero", "Character"); hero.startingPC = "Home";
var stranger = Card("Stranger", "Character"); stranger.startingPC = "Far Hold";
var sword = Card("Sword", "Object"); sword.objectType = ObjectTypeEnum.Weapon;
var ring = Card("Ring", "Object"); ring.objectType = ObjectTypeEnum.Ring;
var beast = Card("Beast", "Army");
var wight = Card("Wight", "Encounter"); wight.birthplaces.Add("Home");
r.Players[0].Hand.AddRange(new[] { vale, hero, stranger, sword, ring, beast, wight });
r.Begin(0);
Check(!r.DestinationChoices(0).Any(), "Destinations offered before any land");
r.Next(); Check(r.Stage == MatchStage.Realm && r.Play(vale), "Land rejected in Realm");
Check(!r.Players[0].Hand.Contains(home) && r.PlayBlockReason(home) != null, "A settlement must never be a hand card");
r.Next(); Check(r.Stage == MatchStage.Destination, "Realm must go to Select Destination");
Check(r.DestinationChoices(0).SequenceEqual(new[] { home, market }), "Choices must be the settlements whose land is down");
Check(r.HasLegalAction() && !r.CanChooseDestination(far) && r.CanChooseDestination(home), "Destination legality wrong");
Check(r.DestinationDemand(0, home) == 3 && r.DestinationDemand(0, market) == 1 && r.DestinationDemand(0, far) == 1, "Demand count wrong: " + r.DestinationDemand(0, home));
Check(r.PreferredDestination(0) == home, "Preferred destination should be the one most hand cards want");
Check(!r.ChooseDestination(far) && r.ChooseDestination(market) && r.ChooseDestination(home), "Choosing/re-choosing failed");
var destination = r.Players[0].Destination;
Check(destination != null && destination.Card == home && r.Players[0].Field.Count(u => u.Card.GetCardType() == CardTypeEnum.PC) == 1, "Only the destination sits on the field");
Check(!r.CanChooseDestination(home) && r.CanChooseDestination(market), "Current destination should not be re-selectable");
Check(r.PreferredDestination(0) == null, "Best choice already taken should mean stay");
r.Next(); Check(r.Stage == MatchStage.Muster, "Destination must go to Muster");
Check(r.CanPlay(beast) && r.CanPlay(hero) && r.CanPlay(wight) && !r.CanPlay(stranger) && !r.CanPlay(sword) && !r.CanPlay(ring), "Muster eligibility at destination wrong");
Check(r.PlayBlockReason(stranger).Contains("Far Hold") && r.PlayBlockReason(ring).Contains("Ring"), "Block reasons should name what is needed");
Check(r.Play(hero) && destination.Tapped, "Playing at the destination must tap it");
Check(!r.CanPlay(wight) && r.PlayBlockReason(wight).Contains("already"), "Second play at a used destination accepted");
Check(r.CanPlay(beast), "Armies must not need the destination");
Check(r.Undo() && !destination.Tapped && r.Players[0].Hand.Contains(hero), "Undo must untap the destination");
Check(r.Play(wight) && r.Players[0].Discard.Contains(wight) && destination.Tapped, "Encounter not investigated");
Check(r.Undo() && r.Players[0].Hand.Contains(wight) && !r.Players[0].Discard.Contains(wight) && !destination.Tapped, "Encounter undo failed");
Check(r.Play(hero), "Hero replay failed");
var heroUnit = r.Players[0].Field.First(u => u.Card == hero);
Check(!r.Play(sword, heroUnit) && r.PlayBlockReason(sword, heroUnit, false).Contains("already"), "Object played at used destination");
while (r.Active == 0) r.Next();
while (r.Active == 1) r.Next();
Check(r.Stage == MatchStage.Draw && r.Players[0].Destination == destination && !destination.Tapped, "Destination must persist and untap on the next turn");
r.Next(); r.Next(); Check(r.Stage == MatchStage.Destination, "Second turn skipped destination");
r.Next(); Check(r.Players[0].Destination == destination, "Staying changed the destination");
Check(r.Play(sword, heroUnit) && heroUnit.Objects.Contains(sword) && destination.Tapped, "Weapon not equipped at a settlement trading in weapons");
Check(!r.CanPlay(ring), "Ring accepted where nobody trades in rings");
// Opponent scoring: the most cards waiting wins, current destination on a tie.
var o = r.Players[1]; o.Field.Add(new MatchRules.Unit { Card = Card("Vale", "Land"), Owner = 1 });
var a = Card("A", "PC"); a.region = "Vale"; var b = Card("B", "PC"); b.region = "Vale"; o.Settlements.AddRange(new[] { a, b });
var wantsB = Card("Wants B", "Character"); wantsB.startingPC = "B"; o.Hand.Add(wantsB);
while (r.Active == 0) r.Next();
r.Next(); r.Next(); Check(r.Active == 1 && r.Stage == MatchStage.Destination, "Opponent destination stage not reached");
Check(r.PreferredDestination(1) == b && r.ChooseDestination(b), "Opponent should travel where its hand cards wait");
o.Hand.Clear(); var wantsA = Card("Wants A", "Character"); wantsA.startingPC = "A"; var wantsB2 = Card("Wants B too", "Character"); wantsB2.startingPC = "B"; o.Hand.AddRange(new[] { wantsA, wantsB2 });
Check(r.PreferredDestination(1) == null, "Tie must keep the current destination");
return "PASS: settlement pool, land-gated choices, one destination on the field, demand scoring, destination-gated characters/encounters/objects, tapping, undo, persistence across turns, and opponent travel preference.";
