void Check(bool value, string message) { if (!value) throw new System.Exception(message); }
var r = new MatchRules();
var land = new CardData { name="Vale", type="Land", goldGranted=3 };
var army = new CardData { name="Army", type="Army", goldRequired=3 };
var ev = new CardData { name="Event", type="Event", goldRequired=3 };
r.Players[0].Hand.AddRange(new[]{land,army,ev});
r.Begin(0);r.Next();r.Play(land);
var first=r.Players[0].Field[0];
var second=new MatchRules.Unit {Card=land,Owner=0};r.Players[0].Field.Add(second);
Check(!r.TapLand(first)&&!first.Tapped,"Realm tapped a land");
r.Next();Check(r.Stage==MatchStage.Destination&&!r.HasLegalAction(),"Realms must go to Select Destination, which skips with no settlements");
r.Next();Check(r.Stage==MatchStage.Muster,"Select Destination must go to Muster");
Check(!r.CanPlay(army)&&r.HasLegalAction(),"Unfunded but affordable Muster skipped");
Check(!first.Tapped&&r.Players[0].Mana[6]==0,"Affordability query mutated state");
Check(r.TapLand(first)&&r.Play(army),"Cannot fund army during Muster");
Check(!r.TapLand(first)&&!second.Tapped,"Duplicate tap or unrelated land changed");
r.Next();Check(!r.HasLegalAction(),"Unsupported event held stage open");
r.ResolveEvent=(c,p,s)=>{};
Check(r.HasLegalAction()&&!r.CanPlay(ev),"Fundable event skipped");
Check(r.TapLand(second)&&r.Play(ev),"Cannot fund event during Events");
Check(!r.HasLegalAction(),"Empty events did not skip");
r.Next();first.Tapped=false;Check(!r.CanTapLand(first),"Attack allows mana tapping");
// --- Gathering on demand: a click on a card taps the lands it needs, the most useful first --------------
var g = new MatchRules();
var hides = new CardData { name="Hides", type="Land", leatherGranted=1 };
var mine = new CardData { name="Mine", type="Land", ironGranted=2 };
var pasture = new CardData { name="Pasture", type="Land", leatherGranted=2 };
var knight = new CardData { name="Knight", type="Army", leatherRequired=2, ironRequired=1 };
var dragon = new CardData { name="Dragon", type="Army", mithrilRequired=1 };
g.Players[0].Hand.AddRange(new[]{knight,dragon});
foreach (var l in new[]{hides,mine,pasture}) g.Players[0].Field.Add(new MatchRules.Unit{Card=l,Owner=0});
g.Begin(0); while (g.Stage!=MatchStage.Muster) g.Next();
Check(!g.CanPlay(knight)&&g.PlayBlockReason(knight,includeReadyMana:true)==null,"Ready lands must count as mana when asked");
Check(g.PlayBlockReason(knight).Contains("2 leather and 1 iron")&&g.PlayBlockReason(knight).Contains("ready lands can pay"),"The shortfall must be named: "+g.PlayBlockReason(knight));
Check(g.Players[0].Mana.Shortfall(knight)=="2 leather and 1 iron"&&g.Players[0].Mana.Help(pasture,knight)==2&&g.Players[0].Mana.Help(hides,knight)==1&&g.Players[0].Mana.Help(mine,knight)==1,"Shortfall or land help wrong");
Check(g.GatherFor(knight)&&g.CanPlay(knight),"Gathering must make the card affordable");
var tapped = g.Players[0].Field.Where(u=>u.Tapped).Select(u=>u.Card.name).ToList();
Check(tapped.Count==2&&tapped.Contains("Pasture")&&tapped.Contains("Mine"),"Gathering must tap the pasture and the mine, not the hides: "+string.Join(",",tapped));
Check(!g.GatherFor(dragon)&&g.PlayBlockReason(dragon).Contains("1 mithril")&&g.PlayBlockReason(dragon).Contains("would not make up"),"An unpayable card must not tap lands for nothing: "+g.PlayBlockReason(dragon));
Check(g.Players[0].Field.Count(u=>u.Tapped)==2,"Gathering for the dragon tapped a useless land");
return "PASS: no Realm tapping; on-demand Muster/Event funding; no premature skip, duplicate grants or query mutation; gathering taps the useful lands and names the shortfall.";
