void Check(bool value, string message) { if(!value) throw new System.Exception(message); }
CardData Card(string name,string type) => new CardData {name=name,type=type};
var r=new MatchRules(); var land=Card("Vale","Land"); land.goldGranted=5;
var pc=Card("Home","PC");pc.region="Vale";
var beast=Card("Beasts","Army");
var hero=Card("Commander","Character");hero.startingPC="Home";
var obj=Card("Object","Object"); var ev=Card("Event","Event");ev.goldRequired=2;
r.Players[0].Hand.AddRange(new[]{land,pc,beast,hero,obj,ev});
var enemyLand=new MatchRules.Unit {Card=Card("Enemy land","Land"),Owner=1,Tapped=true};r.Players[1].Field.Add(enemyLand);
r.Begin(0);Check(!r.HasLegalAction()&&!r.CanPlay(land),"Draw exposed a manual action");
r.Next();Check(r.HasLegalAction()&&r.CanPlay(land)&&!r.CanPlay(pc)&&!r.CanPlay(beast),"Realm legality wrong");
r.Play(land);Check(r.CanPlay(pc),"Land did not unlock PC");r.Play(pc);
Check(!r.HasLegalAction(),"Empty realm did not report no actions");r.Next();
var ownLand=r.Players[0].Field.First(u=>u.Card==land);
Check(r.HasLegalAction()&&r.CanTapLand(ownLand)&&!r.CanTapLand(enemyLand),"Mana ownership invalid");
Check(r.TapLand(ownLand)&&enemyLand.Tapped,"Opponent state changed by own land tap");
Check(!r.HasLegalAction(),"Mana stage still actionable after last land");
r.Next();Check(ownLand.Tapped&&enemyLand.Tapped,"Stage transition untapped lands");
Check(!r.CanPlay(pc)&&r.CanPlay(beast)&&r.CanPlay(hero)&&!r.CanPlay(obj),"Muster eligibility wrong");
r.Play(beast);r.Play(hero);Check(r.CanPlay(obj),"Object recipient not discovered");
var unit=r.Players[0].Field.First(u=>u.Card==beast);Check(!unit.Tapped&&r.IsNewUnit(unit),"New unit should enter untapped but delayed");
r.Next();Check(!r.HasLegalAction(),"Unsupported event should not hold stage open");
r.ResolveEvent=(c,p,state)=>{};
int gold=r.Players[0].Mana[6];Check(r.CanPlay(ev)&&r.CanPlay(ev)&&r.Players[0].Mana[6]==gold,"Legality query spent mana");
Check(r.HasLegalAction(),"Legal event skipped");r.Play(ev);Check(!r.HasLegalAction(),"Empty events still actionable");
r.Next();Check(!r.CanAttack(unit)&&!r.HasLegalAction(),"New units incorrectly attack");
unit.Card.specialAbilities.Add(ObjectCharacterArmySpecialAbilityEnum.Mounted);Check(r.CanAttack(unit)&&r.HasLegalAction(),"Mounted did not permit attack");r.Attack(unit);
r.Next();Check(!r.HasLegalAction(),"No defenders should not hold defense stage");r.Next();Check(!r.HasLegalAction(),"Empty spoils should skip");
Check(ownLand.Tapped&&enemyLand.Tapped,"Lands changed pose between stages");r.Next();
Check(ownLand.Tapped&&!enemyLand.Tapped,"Only the new turn owner's lands should untap");
return "PASS: read-only legality, ownership, stage eligibility, auto-skip predicates, event affordability, untapped new units, Mounted, and turn-only untapping.";
