void Check(bool value, string message) { if(!value) throw new System.Exception(message); }
CardData Card(string name,string type) => new CardData {name=name,type=type};
var r=new MatchRules(); var land=Card("Vale","Land"); land.goldGranted=5;
var pc=Card("Home","PC");pc.region="Vale";
var beast=Card("Beasts","Army");
var hero=Card("Commander","Character");hero.startingPC="Home";
var obj=Card("Object","Object");obj.objectType=ObjectTypeEnum.Ring;pc.objectTypes.Add(ObjectTypeEnum.Ring); var ev=Card("Event","Event");ev.goldRequired=2;
r.Players[0].Hand.AddRange(new[]{land,beast,hero,obj,ev}); r.Players[0].Settlements.Add(pc);
var enemyLand=new MatchRules.Unit {Card=Card("Enemy land","Land"),Owner=1,Tapped=true};r.Players[1].Field.Add(enemyLand);
r.Begin(0);Check(!r.HasLegalAction()&&!r.CanPlay(land),"Draw exposed a manual action");
r.Next();Check(r.HasLegalAction()&&r.CanPlay(land)&&!r.CanPlay(pc)&&!r.CanPlay(beast),"Realm legality wrong");
Check(!r.DestinationChoices(0).Any(),"Settlement offered before its land");r.Play(land);Check(r.DestinationChoices(0).Contains(pc),"Land did not unlock PC");
Check(!r.HasLegalAction(),"Empty realm did not report no actions");r.Next();
Check(r.Stage==MatchStage.Destination&&r.HasLegalAction()&&r.ChooseDestination(pc)&&!r.HasLegalAction(),"Destination stage legality wrong");r.Next();
Check(r.Stage==MatchStage.Travel&&r.Players[0].Destination==null&&!r.HasLegalAction(),"The road is walked before arriving, and an enemy with no units has no attack");r.Next();
Check(r.Stage==MatchStage.Arrival&&r.Players[0].Destination!=null&&r.Players[0].Destination.Card==pc&&r.NoneReady(0)&&r.CanEnter(null)&&r.HasLegalAction(),"Arrival must set the destination and, with nothing ready, offer the champion the way in");
r.Next();Check(r.Stage==MatchStage.Muster&&!r.Players[0].Destination.Tapped,"Staying outside must go on to Muster with the town unentered");
var ownLand=r.Players[0].Field.First(u=>u.Card==land);
Check(r.HasLegalAction()&&r.CanTapLand(ownLand)&&!r.CanTapLand(enemyLand),"Mana ownership invalid");
Check(r.TapLand(ownLand)&&enemyLand.Tapped,"Opponent state changed by own land tap");
Check(r.HasLegalAction(),"Muster must allow deployment after tapping");
Check(ownLand.Tapped&&enemyLand.Tapped,"Stage transition untapped lands");
Check(!r.CanPlay(pc)&&r.CanPlay(beast)&&!r.CanPlay(hero)&&!r.CanPlay(obj),"Muster eligibility wrong: nothing plays at a town before it is entered");
r.Play(beast);var unit=r.Players[0].Field.First(u=>u.Card==beast);Check(unit.Tapped&&!r.CanEnter(unit),"A recruit must enter tapped, and a tapped unit cannot walk into town");
var scout=new MatchRules.Unit {Card=Card("Scout","Army"),Owner=0};r.Players[0].Field.Add(scout);
Check(r.NeedsEntering()&&r.HasLegalAction()&&r.CanEnter(scout)&&r.Enter(scout)&&scout.Tapped&&r.Players[0].Destination.Entered,"Entering from Muster failed");
Check(r.CanPlay(hero),"An entered town must host its characters");r.Play(hero);Check(r.CanPlay(obj),"An entered town must keep hosting plays");
Check(r.CanDiscard(ev)&&r.HasLegalAction(),"An event with no effect must be discardable during Muster, and hold the stage for it");
r.Next();Check(!r.CanDiscard(ev)&&!r.HasLegalAction(),"Unsupported event should not hold the Events stage open");
r.ResolveEvent=(c,p,state)=>{};
int gold=r.Players[0].Mana[6];Check(r.CanPlay(ev)&&r.CanPlay(ev)&&r.Players[0].Mana[6]==gold,"Legality query spent mana");
Check(r.HasLegalAction(),"Legal event skipped");r.Play(ev);Check(!r.HasLegalAction(),"Empty events still actionable");
r.Next();Check(r.Stage==MatchStage.Spoils&&!r.HasLegalAction(),"Empty spoils should skip");
Check(ownLand.Tapped&&enemyLand.Tapped,"Lands changed pose between stages");r.Next();
Check(ownLand.Tapped&&!enemyLand.Tapped,"Only the new turn owner's lands should untap");
// The enemy company's road is our attack window: ready units that are not new and can fight on the ground.
var enemyHome=Card("Enemy home","PC");enemyHome.region="Enemy land";r.Players[1].Settlements.Add(enemyHome);r.StartAt(1,enemyHome);
r.Next();r.Next();Check(r.Stage==MatchStage.Destination&&!r.HasLegalAction(),"Staying put needs no choice");r.Next();
Check(r.Stage==MatchStage.Travel&&r.Phase==TravelPhase.Attack&&r.Attacker==0&&r.Travel.Stops.Count==1,"Holding still is a one-stop road with our attack window");
Check(unit.Tapped&&!r.CanAttack(unit),"A recruit is still mustering through the enemy's next road: it readies at its owner's turn start");
unit.Tapped=false;Check(r.CanAttack(unit)&&r.HasLegalAction(),"A ready unit must be able to raid the road");
var hero2=r.Players[0].Field.First(u=>u.Card==hero);hero2.Tapped=true;Check(!r.CanAttack(hero2),"A tapped unit must not attack");r.Attack(unit);
r.Next();Check(r.Phase==TravelPhase.Defend&&!r.HasLegalAction(),"No defenders should not hold the defence");r.Next();
Check(r.Stage==MatchStage.Muster&&r.Players[1].Life==20-unit.Card.GetCombatStats().attack,"An unblocked road attack must hit the travelling company");
return "PASS: read-only legality, ownership, destination gating, stage eligibility, auto-skip predicates, event affordability, tapped recruits, road attacks, and turn-only untapping.";
